# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170627_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistencylevel',
            name='type_en_us',
            field=models.CharField(max_length=20, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='consistencylevel',
            name='type_pt_br',
            field=models.CharField(max_length=20, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='discretization',
            name='type_en_us',
            field=models.CharField(max_length=20, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='discretization',
            name='type_pt_br',
            field=models.CharField(max_length=20, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_en_us',
            field=models.CharField(max_length=20, null=True, verbose_name='variable'),
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_pt_br',
            field=models.CharField(max_length=20, null=True, verbose_name='variable'),
        ),
    ]
