# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170627_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discretization',
            name='type',
            field=models.CharField(max_length=30, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='discretization',
            name='type_en_us',
            field=models.CharField(max_length=30, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='discretization',
            name='type_pt_br',
            field=models.CharField(max_length=30, null=True, verbose_name='type'),
        ),
    ]
