# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_serie_id', models.IntegerField(verbose_name='temporal serie id')),
                ('discretization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Discretization', verbose_name='discretization')),
                ('original_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.OriginalSerie', verbose_name='original serie')),
            ],
            options={
                'verbose_name': 'Reduced Serie',
                'verbose_name_plural': 'Reduced Series',
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('type_en_us', models.CharField(max_length=20, null=True, verbose_name='type')),
                ('type_pt_br', models.CharField(max_length=20, null=True, verbose_name='type')),
                ('stats_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stats', verbose_name='stats type')),
            ],
            options={
                'verbose_name': 'Reduction',
                'verbose_name_plural': 'Reductions',
            },
        ),
        migrations.CreateModel(
            name='RollingMeanSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_serie_id', models.IntegerField(verbose_name='temporal serie id')),
                ('discretization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Discretization', verbose_name='discretization')),
                ('serie_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.OriginalSerie', verbose_name='original serie')),
            ],
            options={
                'verbose_name': 'Rolling mean serie',
                'verbose_name_plural': 'Rolling mean series',
            },
        ),
        migrations.AddField(
            model_name='reducedserie',
            name='reduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Reduction', verbose_name='reduction'),
        ),
    ]
