# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='type_en_us',
            field=models.CharField(max_length=20, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='reduction',
            name='type_pt_br',
            field=models.CharField(max_length=20, null=True, verbose_name='type'),
        ),
    ]
