# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='hydrologic_year_type',
            field=models.CharField(choices=[('flood', 'flood'), ('drought', 'drought')], default='flood', max_length=50, verbose_name='temporal serie id'),
            preserve_default=False,
        ),
    ]
