# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_reduction_hydrologic_year_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducedserie',
            name='limiar',
            field=models.FloatField(null=True, verbose_name='limiar'),
        ),
    ]
