# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_reducedserie_limiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('abreviation', models.CharField(max_length=5, verbose_name='abreviation')),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilityCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(verbose_name='alpha')),
                ('betha', models.FloatField(verbose_name='betha')),
                ('kappa', models.FloatField(verbose_name='kappa')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Distribution', verbose_name='distribution')),
            ],
        ),
        migrations.CreateModel(
            name='ResamplingSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='length')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None, verbose_name='data')),
                ('is_base_curve', models.BooleanField(verbose_name='Is base curve')),
                ('curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.ProbabilityCurve', verbose_name='curve')),
            ],
        ),
        migrations.RemoveField(
            model_name='rollingmeanserie',
            name='discretization',
        ),
        migrations.RemoveField(
            model_name='rollingmeanserie',
            name='serie_original',
        ),
        migrations.AlterField(
            model_name='reduction',
            name='hydrologic_year_type',
            field=models.CharField(choices=[('flood', 'flood'), ('drought', 'drought')], max_length=50, verbose_name='hydrologic year type'),
        ),
        migrations.DeleteModel(
            name='RollingMeanSerie',
        ),
    ]
