# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 18:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20171213_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='resamplingserie',
            name='probabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None, verbose_name='probabilities'),
            preserve_default=False,
        ),
    ]
